config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from explorea.events import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('events/', include('explorea.events.urls', namespace='events')),
    path('accounts/', include('explorea.accounts.urls', namespace='accounts')),
    path('cart/', include('explorea.cart.urls', namespace='cart')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

explorea/accounts/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.login, {'template_name': 'accounts/login.html'}, name='login'),
    path('logout/', auth_views.logout, {'next_page': '/'}, name='logout'),
    
    path('register/', views.RegisterView.as_view(), name='register'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/edit/', views.EditProfileView.as_view(), name='edit_profile'),
    path('change-password/', views.ChangePasswordView.as_view(), name='change_password'),

    path('reset-password/', auth_views.password_reset, 
        {'template_name': 'accounts/reset_password.html', 
        'post_reset_redirect':'accounts:password_reset_done',
        'email_template_name':'accounts/reset_password_email.html'}, name='reset_password'),
    path('reset-password/done/', auth_views.password_reset_done,  name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', auth_views.password_reset_confirm, 
        {'post_reset_redirect':'accounts:password_reset_complete'}, name='password_reset_confirm'),
    path('reset-password/complete/', auth_views.password_reset_complete, name='password_reset_complete'),

    path('hosts/', views.HostListView.as_view(), name='host_list'),
    path('become-host/', views.BecomHostView.as_view(), name='become_host'),
    url(r'^become-host/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', views.ActivateHost.as_view(), 
        name='activate_host'),
    path('host/profile/<username>/', views.HostProfileView.as_view(), name='host_profile'),

    path('ajax/validate_exists/', views.ValidateRegisterFormView.as_view(), name='validate_register_form'),
]

explorea/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartDetailView.as_view(), name='detail'),
    path('add/<slug:event_slug>/', views.CartAddView.as_view(), name='add'),
    path('remove/<int:product_id>', views.CartRemoveView.as_view(), name='remove'),
]

explorea/events/urls.py
from django.urls import path

from . import views

app_name = 'events'

urlpatterns = [
    path('new/',
         views.CreateEventView.as_view(),
         name='create_event'),

    path('mine/',
         views.MyEventsView.as_view(),
         name='my_events'),

    path('search/',
         views.EventSearchView.as_view(),
         name='search'),
    
    path('detail/<slug:slug>/',
         views.EventDetailView.as_view(),
         name='detail'),

    path('update/<slug:slug>/', 
         views.UpdateEventView.as_view(),
         name='update_event'),

    path('delete/<slug:slug>/',
         views.DeleteEventView.as_view(),
         name='delete_event'),

    path('<slug:event_slug>/update-run/<int:event_run_id>/', 
          views.UpdateEventRunView.as_view(), 
          name='update_event_run'),
    
    path('<slug:event_slug>/delete-run/<int:event_run_id>/', 
         views.DeleteEventRunView.as_view(),
         name='delete_event_run'),
    
    path('<slug:event_slug>/new-run/',
         views.CreateEventRunView.as_view(),
         name='create_event_run'),

    path('<category>/',
         views.EventListView.as_view(),
         name='events'),
]

explorea/cart/models.py
from django.db import models

# Create your models here.

explorea/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from core.validators import validate_human_name
from .models import Profile

UserModel = get_user_model()

class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=100, validators=[validate_human_name,])
    last_name = forms.CharField(max_length=100, validators=[validate_human_name,])

    class Meta:
        model = UserModel
        fields = [
            'username',
            'email',
            'first_name',
            'last_name',
            'password1',
            'password2',
        ]

class EditUserForm(UserChangeForm):
    first_name = forms.CharField(max_length=100, validators=[validate_human_name,])
    last_name = forms.CharField(max_length=100, validators=[validate_human_name,])
    
    class Meta:
        model = UserModel
        fields = [
            'username',
            'email',
            'first_name',
            'last_name',
            'password'
        ]

class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['about', 'avatar']

explorea/cart/forms.py
from django import forms

from explorea.events.models import EventRun

class PositiveIntegerField(forms.IntegerField):

    def validate(self, value):
        super().validate(value)
        if value < 1:
            raise forms.ValidationError('Only positive integer allowed')

class CartAddForm(forms.ModelForm):
    quantity = PositiveIntegerField(initial=0)
    product_id = forms.CharField(max_length=10, widget=forms.HiddenInput())
    update = forms.BooleanField(required=False, initial=False, 
                                    widget=forms.HiddenInput)
    current_quantity = forms.IntegerField(required=False, initial=0, 
                                   widget=forms.HiddenInput)

    class Meta:
        model = EventRun
        fields = [
            'quantity', 
            'product_id', 
            'update', 
            'current_quantity',
        ]

    def clean(self):
        super().clean()
        product_id = self.cleaned_data.get('product_id')
        quantity = self.cleaned_data.get('quantity')
        update = self.cleaned_data.get('update')
        current_quantity = 0 if update else  self.cleaned_data.get('current_quantity')
        
        if all([product_id, quantity]) and current_quantity >= 0:
            
            try:
                run = self._meta.model.objects.get(pk=int(product_id))

                if run.seats_available < int(quantity) + int(current_quantity):
                    self.add_error('quantity', 'Not enough items available')
            except self._meta.model.DoesNotExist:
                self.add_error('product_id', 'Requested item does not exist')

explorea/accounts/views.py
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_decode
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes
from django.contrib.auth import get_user_model
from django.http import HttpResponseRedirect, JsonResponse

from django.views.generic import TemplateView, ListView, DetailView, View
from django.views.generic.base import TemplateResponseMixin, ContextMixin
from django.views.generic.edit import CreateView, UpdateView, FormMixin, ProcessFormView
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import RegisterForm, EditUserForm, EditProfileForm
from .models import Profile

token_generator = PasswordResetTokenGenerator()
UserModel = get_user_model()


class MultipleFormsMixin(ContextMixin):
    form_classes = {}
    initial = {}
    success_url = ''

    def forms_valid(self, forms):
        return HttpResponseRedirect(self.get_success_url())

    def forms_invalid(self, forms):
        return self.render_to_response(self.get_context_data(forms=forms))

    def get_context_data(self, **kwargs):
        if 'forms' not in kwargs:
            forms = self.get_forms() 
            for name, form in forms.items():
                kwargs[name] = form
        return super().get_context_data(**kwargs)

    def get_forms(self, form_classes=None):
        """Return a dict of form instances to be used in this view."""
        if form_classes is None:
            forms = self.get_form_classes()
        kwargs = self.get_forms_kwargs()

        return {name:form(**kwargs[name]) for name, form in forms.items()}       
    
    def get_form_classes(self):
        return self.form_classes.copy()

    def get_forms_kwargs(self):
        kwargs = {}
        for name, form in self.form_classes.items():
            kwargs[name] = {
                'initial': self.get_initial(),
            }
            if self.request.method in ('POST', 'PUT'):
                kwargs[name].update({
                    'data': self.request.POST,
                    'files': self.request.FILES,
                })
        return kwargs

    def get_initial(self):
        return self.initial.copy()

    def get_success_url(self):
        if not self.success_url:
            raise ImproperlyConfigured("No URL to redirect to. Provide a success_url.")
        return str(self.success_url)


class MultipleModelFormsMixin(MultipleFormsMixin):
    instances =  {}

    def dispatch(self, request, *args, **kwargs):
        self.instances = self.get_instances()
        return super().dispatch(request, *args, **kwargs)

    def get_instances(self):
        instances = {}
        for name in self.form_classes:
            instances[name]= None
        return instances

    def forms_valid(self, forms):
        for form in forms:
            form.save()
        return super().forms_valid(forms)

    def get_forms_kwargs(self):
        kwargs = super().get_forms_kwargs()
        for name, form in self.form_classes.items():
            kwargs[name].update({
                'instance': self.instances[name]
            })
        return kwargs


class ProcessMultipleFormsView(MultipleFormsMixin, TemplateResponseMixin,
                               ProcessFormView):

    def get(self, request, *args, **kwargs):
        return self.render_to_response(self.get_context_data())

    def post(self, request, *args, **kwargs):
        self.forms = self.get_forms()
        if all(form.is_valid for form in self.forms.values()):
            return self.forms_valid(self.forms.values())
        else:
            return self.forms_invalid(self.forms.values())


class ProcessMultipleModelFormsView(MultipleModelFormsMixin, ProcessMultipleFormsView):
    pass


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/profile.html'


class RegisterView(CreateView):
    model = UserModel
    form_class = RegisterForm
    template_name = 'accounts/register.html'

    def form_valid(self, form):
        user = form.save()
        raw_password = form.cleaned_data.get('password1')
        user = authenticate(username=user.email, password=raw_password)
        login(self.request, user)

        return redirect('accounts:profile')


class EditProfileView(LoginRequiredMixin, ProcessMultipleModelFormsView):
    template_name = 'accounts/edit_profile.html'
    form_classes = {'user_form': EditUserForm, 'profile_form': EditProfileForm}
    success_url = reverse_lazy('accounts:profile')

    def get_forms_kwargs(self):
        kwargs = super().get_forms_kwargs()
        kwargs['user_form'].update({
                'instance': self.request.user
        })
        kwargs['profile_form'].update({
                'instance': self.request.user.profile 
        })
        return kwargs


class ChangePasswordView(LoginRequiredMixin, UpdateView):
    model = UserModel
    form_class = PasswordChangeForm
    template_name = 'accounts/change_password.html'
    success_url = reverse_lazy('accounts:profile')

    def form_valid(self, form):
        self.object = form.save()
        update_session_auth_hash(self.request, self.object)
        return HttpResponseRedirect(self.get_success_url())

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.pop('instance')
        kwargs.update({'user': self.object})
        return kwargs

    def get_object(self):
        return self.request.user


class HostListView(ListView):
    model = Profile
    template_name = 'accounts/host_list.html'
    context_object_name = 'profiles'

    def get_queryset(self):
        profiles = Profile.objects.filter(is_host=True)
        profiles = profiles.exclude(user__pk=self.request.user.id)
        return profiles


class HostProfileView(LoginRequiredMixin, DetailView):
    model = UserModel
    slug_url_kwarg = 'username'
    slug_field = 'username'
    context_object_name = 'host'
    template_name = 'accounts/host_profile.html'


class BecomHostView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/verification_sent.html'

    def get(self, request, *args, **kwargs):
        verification_email_template = 'accounts/host_verification_email.html'
        email_context = {
            'user': request.user,
            'domain': get_current_site(request).domain,
            'uidb64': urlsafe_base64_encode(force_bytes(request.user.pk)).decode(),
            'token': token_generator.make_token(request.user)
        }

        html_body = render_to_string(verification_email_template, email_context)
        subject = 'Explorea Host Verification'
        from_email = 'admin@explorea.com'
        to_email = request.user.email
        
        email = EmailMessage(subject, html_body, from_email, [to_email])
        email.send()

        return super().get(request, *args, **kwargs)

class ActivateHost(TemplateView):

    def get(self, request, *args, **kwargs):
        try:
            uidb64 = self.kwargs['uidb64']
            token = self.kwargs['token']
            uid = urlsafe_base64_decode(uidb64).decode()
            user = UserModel._default_manager.get(pk=uid)
        except (TypeError, ValueError, OverflowError, UserModel.DoesNotExist):
            user = None

        if user is not None and token_generator.check_token(user, token):
            user.profile.is_host = True
            hosts_group = Group.objects.get(name='hosts')
            user.groups.add(hosts_group)
            user.profile.save()
            return render(request, 'accounts/verification_complete.html')

        else:
            return render(request, 'accounts/invalid_link.html')

class ValidateFieldExistValueView(View):

    def post(self, request, *args, **kwargs):

        name = self.request.POST['field_name']
        value = self.request.POST['field_value']

        data = {
            'exists': self.model.objects.filter(**{name: value}).exists()
        }

        if data['exists']:
            data['error_message'] = 'The {} {} already exists'.format(*(name, value))

        return JsonResponse(data)

class ValidateRegisterFormView(ValidateFieldExistValueView):
    validated_fields = ['username', 'email']
    model = UserModel

explorea/cart/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView, FormView, View
from django.views.generic.detail import SingleObjectMixin
from django.contrib import messages

from explorea.events.models import Event, EventRun
from .forms import CartAddForm


class CartDetailView(TemplateView):
    template_name = "cart/cart_detail.html"


class CartAddView(SingleObjectMixin, FormView):
    model = Event
    form_class =  CartAddForm
    template_name = 'events/event_detail.html'
    slug_url_kwarg = 'event_slug'

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def get_success_url(self):
        return self.object.get_absolute_url()

    def form_valid(self, form):

        self.request.cart.add(**form.cleaned_data)

        if form.cleaned_data['update']:
            messages.success(self.request, 'Cart has been updated')
            return redirect('cart:detail')
        else:
            messages.success(self.request, 'The run has been added to the cart')
            return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form):
        if form.cleaned_data['update']:
            messages.error(self.request, 'The cart could not be updated')
            return redirect('cart:detail')
        else:
            messages.error(self.request, 'The run could not be added into the cart')
            return HttpResponseRedirect(self.get_success_url())        
        

class CartRemoveView(View):

    def get(self, request, *args, **kwargs):
        self.request.cart.remove(self.kwargs['product_id'])
        return redirect('cart:detail')

explorea/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block content %}
<form method='POST'>
    {% csrf_token %}

    {% for field in form.visible_fields %}
        {% for error in field.errors %}
        {{ error }}
        {% endfor %}

        <p>{{ field.label_tag}}{{ field }}</p>

    {% endfor %}


    <input type="submit" value="Change">
</form>
{% endblock content %}

explorea/templates/accounts/edit_profile.html
{% extends 'base.html' %} 

{% block title %}
<title>Profile</title>
{% endblock title %}

{% block content %}
<div>

  <h2>Edit your profile</h2>
  
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in user_form.visible_fields %}
        {% for error in field.errors %}
        {{ error }}
        {% endfor %}

        {% if field.label != 'Password' %}
        <p>{{ field.label_tag}}{{ field }}</p>
        {% endif %}
        

    {% endfor %}

    {% for field in profile_form.visible_fields %}
        {% for error in field.errors %}
        {{ error }}
        {% endfor %}
        <p>{{ field.label_tag}}{{ field }}</p>

    {% endfor %}

    <button type="submit">Save</button>
  </form>
  
</div>
{% endblock content %}

explorea/templates/accounts/host_list.html
{% extends 'base.html' %}
{% load account_tags %}
{% load static%}

{% block title %}
<title>Our Hosts</title>
{% endblock title %}

{% block content %}

{% for profile in profiles %}
<div>
    <a href="{{ profile.get_absolute_url }}">
         {% if  user.profile.avatar|has:'url' %}
            <img src="{{ user.profile.avatar.url }}" alt='{{ profile.user.username }}'>
        {% else %}
            <img src="{% static 'img/avatar.png' %}" alt='Not Available'>
        {% endif %}

        <p>{{ profile.user.username }}</p>
    </a>
</div>
{% empty %}
    {% if user|has:'profile' and user.profile.is_host %}
    <p>You are our only host right now</p>
    {% else %}
    <p>There are no hosts at the moment</p>
    {% endif %}
{% endfor %}

{% if user|has:'profile' and not user.profile.is_host %}
<div>
    <a href="{% url 'accounts:become_host' %}" class="button-gold">Become a host</a>
</div>
{% endif %}

{% endblock content %}

explorea/templates/accounts/host_profile.html
{% extends 'base.html' %}
{% load static %}
{% load account_tags %}

{% block content %}
<br>
<table>
    <tr>
        <td>
        {% if  host.profile.avatar|has:'url' %}
            <img src="{{ host.profile.avatar.url }}">
        {% else %}
            <img src="{% static 'img/avatar.png' %}">
        {% endif %}
        </td>

    </tr>
    <tr>
        <td>hostname: </td><td>{{ host.hostname }}</td>
    </tr>
    <tr>
        <td>First Name: </td><td>{{ host.first_name }}</td>
    </tr>
    <tr>
        <td>Last Name: </td><td>{{ host.last_name }}</td>
    </tr>
    <tr>
        <td>Email: </td><td>{{ host.email }}</td>
    </tr>
    <tr>
        <td>Joined: </td><td>{{ host.date_joined }}</td>
    </tr>
    <tr>
        <td>About Me: </td><td>{{ host.profile.about }}</td>
    </tr>
</table>
{% endblock content %}

explorea/templates/accounts/host_verification_email.html
<p>Dear {{ user.username }}</p>

<p>You are one step from becoming host at Explorea. Please click the below link button to complete the verification:</p>

<a href="http://{{ domain }}{% url 'accounts:activate_host' uidb64 token %}" target="_blank">Verify</a>


<p>Thanks for using our site!</p>

<p>The Explorea team</p>

explorea/templates/accounts/invalid_link.html
{% extends 'base.html' %}

{% block title %}
<title>Link invalid</title>
{% endblock title %}

{% block content %}
<p>Unfortunately we were not able to perform the verification. Is it possible that your link is older than 7 days?</p>

<p><a href="{% url 'accounts:become_host' %}">Apply again</a></p>
{% endblock content %}

explorea/templates/accounts/logged_out.html
{% extends 'base.html' %}

{% block content %}
<h2>Ciao</h2>
<p>You have been logged out. But if you decide to log in again, we will be happy to see you here.</p>
{% endblock content %}

explorea/templates/accounts/login.html
{% extends 'base.html' %} 

{% block title %}<title>Login</title>{% endblock title %}

{% block content %}
<div class="grid_container">
    <div class="login-image">
      
    </div>
    <div class="login_form">
        

        <form method="post">
            <h2>Login</h2>
            {% csrf_token %}
            {% for field in form.visible_fields %}
                <p>{{ field.label_tag }}{{ field }}</p>
            {% endfor %}

            <div>
                <button type="submit">Log in</button>
                <a class="forgot-pass" href="{% url 'accounts:reset_password' %}">Forgot password</a>
            </div>

        </form>

    </div>

</div>
{% endblock %}

explorea/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% load account_tags %}

{% block content %}
<br>
<table>
    <tr>
        <td>
        {% if  user.profile.avatar|has:'url' %}
            <img src="{{ user.profile.avatar.url }}">
        {% else %}
            <img src="{% static 'img/avatar.png' %}">
        {% endif %}
        </td>

    </tr>
    <tr>
        <td>Username: </td><td>{{ user.username }}</td>
    </tr>
    <tr>
        <td>First Name: </td><td>{{ user.first_name }}</td>
    </tr>
    <tr>
        <td>Last Name: </td><td>{{ user.last_name }}</td>
    </tr>
    <tr>
        <td>Email: </td><td>{{ user.email }}</td>
    </tr>
     <tr>
        <td>Joined: </td><td>{{ user.date_joined }}</td>
    </tr>
</table>


<br><br>

{% if user.is_authenticated %}
<a href="/accounts/profile/edit/">Edit</a>
<a href="/accounts/change-password/">Change Password</a>
{% endif %}

{% endblock content %}

explorea/templates/accounts/register.html
{% extends 'base.html' %} 

{% block title %}<title>Register</title>{% endblock title %}

{% block content %}
<div class="grid_container">
    <div class="login-image">
      
    </div>
    <div class="register_form">
        

        <form id='register-form' method="post" data-validation="{% url 'accounts:validate_register_form' %}">
            <h2>Register</h2>
            {% csrf_token %}
            {% for field in form.visible_fields %}
                <p>{{ field.label_tag }}{{ field }}</p>
                {% for error in field.errors %}
                    <div class="error" >
                    {{ error }}
                    </div>
                {% endfor %}
            {% endfor %}

            <button type="submit">Sign up</button>
        </form>

    </div>

</div>
{% endblock %}

explorea/templates/accounts/reset_password.html
{% extends 'base.html' %} 

{% block title %}
<title>Password Reset</title>
{% endblock title %}

{% block content %}
<div>

  <h2>Password Reset</h2>
  <p>Enter your email below and click "Submit". We will send you the reset link to your email immediately.</p>

  <form method="post">
    {% csrf_token %}

    {% for field in form.visible_fields %}

        {% for error in field.errors %}
        {{ error }}
        {% endfor %}

        <p>{{ field.label_tag}} {{ field }}</p>

    {% endfor %}
    
    <button type="submit">Submit</button>
  </form>
  
</div>
{% endblock content %}

explorea/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

explorea/templates/accounts/verification_complete.html
{% extends 'base.html' %}

{% block title %}
<title>Link invalid</title>
{% endblock title %}

{% block content %}
<p>Congratulations, you can now begin to earn your money.</p>

<p><a href="{% url 'events:create_event' %}"><strong>Create your first event</strong></a></p>
{% endblock content %}

explorea/templates/accounts/verification_sent.html
{% extends 'base.html' %}

{% block title %}
<title>Email sent</title>
{% endblock title %}

{% block content %}
<p>Time to check your email. We have sent you and email to <strong>{{ request.user.email }}</strong> with verification link. Please, click it and we are done</p>

<p>You can close this tab if your want</p>
{% endblock content %}