config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from explorea.events import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('events/', include('explorea.events.urls', namespace='events')),
    path('accounts/', include('explorea.accounts.urls', namespace='accounts')),
    path('cart/', include('explorea.cart.urls', namespace='cart')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

explorea/accounts/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.login, {'template_name': 'accounts/login.html'}, name='login'),
    path('logout/', auth_views.logout, {'next_page': '/'}, name='logout'),
    
    path('register/', views.RegisterView.as_view(), name='register'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/edit/', views.EditProfileView.as_view(), name='edit_profile'),
    path('change-password/', views.ChangePasswordView.as_view(), name='change_password'),

    path('reset-password/', auth_views.password_reset, 
        {'template_name': 'accounts/reset_password.html', 
        'post_reset_redirect':'accounts:password_reset_done',
        'email_template_name':'accounts/reset_password_email.html'}, name='reset_password'),
    path('reset-password/done/', auth_views.password_reset_done,  name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', auth_views.password_reset_confirm, 
        {'post_reset_redirect':'accounts:password_reset_complete'}, name='password_reset_confirm'),
    path('reset-password/complete/', auth_views.password_reset_complete, name='password_reset_complete'),

    path('hosts/', views.HostListView.as_view(), name='host_list'),
    path('become-host/', views.BecomHostView.as_view(), name='become_host'),
    url(r'^become-host/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', views.ActivateHost.as_view(), 
        name='activate_host'),
    path('host/profile/<username>/', views.HostProfileView.as_view(), name='host_profile'),

    path('ajax/validate_exists/', views.ValidateRegisterFormView.as_view(), name='validate_register_form'),
]

explorea/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartDetailView.as_view(), name='detail'),
    path('add/<slug:event_slug>/', views.CartAddView.as_view(), name='add'),
    path('remove/<int:product_id>', views.CartRemoveView.as_view(), name='remove'),
]

explorea/events/urls.py
from django.urls import path

from . import views

app_name = 'events'

urlpatterns = [
    path('new/',
         views.CreateEventView.as_view(),
         name='create_event'),

    path('mine/',
         views.MyEventsView.as_view(),
         name='my_events'),

    path('search/',
         views.EventSearchView.as_view(),
         name='search'),
    
    path('detail/<slug:slug>/',
         views.EventDetailView.as_view(),
         name='detail'),

    path('update/<slug:slug>/', 
         views.UpdateEventView.as_view(),
         name='update_event'),

    path('delete/<slug:slug>/',
         views.DeleteEventView.as_view(),
         name='delete_event'),

    path('<slug:event_slug>/update-run/<int:event_run_id>/', 
          views.UpdateEventRunView.as_view(), 
          name='update_event_run'),
    
    path('<slug:event_slug>/delete-run/<int:event_run_id>/', 
         views.DeleteEventRunView.as_view(),
         name='delete_event_run'),
    
    path('<slug:event_slug>/new-run/',
         views.CreateEventRunView.as_view(),
         name='create_event_run'),

    path('<category>/',
         views.EventListView.as_view(),
         name='events'),
]

explorea/accounts/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse


def image_dir(instance, filename):
    return 'user_{}/profile_{}'.format(instance.user.id, filename)

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE, primary_key=True)
    is_host = models.BooleanField(default=False)
    about = models.TextField(max_length=500)
    avatar = models.ImageField('Upload your photo', 
        upload_to=image_dir, null=True)

    def get_absolute_url(self):
        return reverse('accounts:host_profile', args=[self.user.username])

explorea/cart/models.py
from django.db import models

# Create your models here.

explorea/events/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.db.models import Max, F, Q
from django.utils import timezone
from django.urls import reverse

from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill


def get_related_attr(obj, attrs):
    related_obj = obj
    for attr in attrs:
        related_obj = getattr(related_obj, attr)
    return related_obj

def thumbnail_image_url(instance, filename):
    '''upload_to for Event thumbnail image'''
    return 'user_{0}/thumb_{1}'.format(instance.host.id, filename) 


def main_image_url(instance, filename):
    '''upload_to for Event main image'''
    return 'user_{0}/main_{1}'.format(instance.host.id, filename) 

def album_image_url(instance, filename):
    '''upload_to for Image model'''
    return 'user_{0}/{1}/{2}'.format(instance.album.event.host.id, 
        instance.album.title, filename)


class EventQuerySet(models.QuerySet):

    def filter_by_category(self, category=None):
        db_equivalent = ''
        for pair in self.model.CATEGORY_CHOICES:
            if pair[1] == category:
                db_equivalent = pair[0]
                break
        else:
            return self.all()

        return self.filter(category=db_equivalent)

    def filter_available(self, date_from=None, date_to=None, guests=None):
        # filter first all the eventruns and then get the ids to events     
        date_from = date_from or timezone.now().date()

        if date_to:
            qs = EventRun.objects.filter(date__range=(date_from, date_to))
        else:
            qs = EventRun.objects.filter(date__gte=date_from)

        if guests:
            qs = qs.filter(seats_available__gte=guests)

        return self.filter(pk__in=[qs.values_list('event', flat=True)])


class EventManager(models.Manager):
    
    def get_queryset(self):
        return EventQuerySet(self.model, using=self._db)


    def search(self, query=None):
        lookup = (
            Q(name__icontains=query) |
            Q(description__icontains=query) |
            Q(location__icontains=query)
        )
        return self.filter(lookup).distinct()



class EventRunQuerySet(models.QuerySet):

    def filter_by_category(self, category=None):
        db_equivalent = ''
        for pair in Event.CATEGORY_CHOICES:
            if pair[1] == category:
                db_equivalent = pair[0]
                break
        else:
            return self.all()

        return self.filter(event__category=db_equivalent)

    def filter_available(self, date_from=None, date_to=None, guests=None):
        # filter first all the eventruns and then get the ids to events     
        date_from = date_from or timezone.now().date()

        if date_to:
            qs = self.filter(date__range=(date_from, date_to))
        else:
            qs = self.filter(date__gte=date_from)

        if guests:
            qs = qs.filter(seats_available__gte=guests)

        return qs

    def filter_first_available(self, date_from=None, date_to=None, guests=None, sort_by='date'):

        if 'postgresql' in settings.DATABASES['default']['ENGINE']:
            qs = self.filter_available(date_from, date_to, guests)
            qs = qs.order_by('event_id', 'date', 'time').distinct('event_id')
            return qs

        qs = self.filter_available(date_from, date_to, guests).order_by('date', 'time')

        event_ids = []
        filtered=[]
        for run in qs:
            if not run.event.id in event_ids:
                filtered.append(run)
                event_ids.append(run.event.id)

        reverse, fields = (sort_by.startswith('-'), sort_by.lstrip('-').split('__'))

        criterion = lambda obj: get_related_attr(obj, fields)

        result =  sorted(filtered, key= criterion, reverse=reverse)
        return result




class EventRunManager(models.Manager):
    
    def get_queryset(self):
        return EventRunQuerySet(self.model, using=self._db)

    def search(self, query=None):
        lookup = (
            Q(event__name__icontains=query) |
            Q(event__description__icontains=query) |
            Q(event__location__icontains=query)
        )
        return self.filter(lookup).distinct()


class Event(models.Model):

    FUN = 'FN'
    RELAX = 'RX'
    EXP = 'EX'
    SIGHTS = 'SI'

    CATEGORY_CHOICES= (
        (FUN, 'fun'),
        (RELAX, 'relax'),
        (EXP, 'experience'),
        (SIGHTS, 'sights')
    )

    host = models.ForeignKey(settings.AUTH_USER_MODEL,
            on_delete=models.CASCADE) 
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True, null=True)
    description = models.TextField(max_length=1000)
    location = models.CharField(max_length=500)
    created = models.DateTimeField(auto_now_add=True, null=True)
    thumbnail = ProcessedImageField(upload_to=thumbnail_image_url,
        processors=[ResizeToFill(300,200)],
        format='PNG',
        options={'quality':60},
        null=True,
        blank=True)
    main_image = ProcessedImageField(upload_to=main_image_url,
        processors=[ResizeToFill(500,600)],
        format='PNG',
        options={'quality':100},
        null=True,
        blank=True)
    category = models.CharField(
        max_length=20,
        choices = CATEGORY_CHOICES,
        default = FUN,
    )

    objects = EventManager()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        unique_together = (("name", "host"),)

    def active_runs(self):
        today = timezone.now().date()
        return self.eventrun_set.filter(date__gte=today)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name + '-with-' + self.host.username)
        super().save(*args, **kwargs)
        
        if not hasattr(self, 'album'):
            Album.objects.create(event=self)


    def get_absolute_url(self):
        return reverse('events:detail', args=[self.slug])

class EventRun(models.Model):

    event = models.ForeignKey(Event, 
        on_delete=models.CASCADE)
    date = models.DateField(blank=False, null=False)
    time = models.TimeField(blank=False, null=False)
    seats_available = models.PositiveIntegerField(blank=False, null=False)
    price = models.DecimalField(max_digits=10, 
        decimal_places=2, blank=False, null=False)

    objects = EventRunManager()

    def __str__(self):
        return '{}|{} ({})'.format(self.date, self.event, self.event.category)

    class Meta:
        ordering = ['date', 'time']

class Album(models.Model):
    event = models.OneToOneField(Event, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, null=True)
    created = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if not self.title:
            self.title = "album_" + self.event.name
        super().save(*args, **kwargs)

    def __str__(self):
        return '{}'.format(self.title)


class Image(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    image = ProcessedImageField(upload_to=album_image_url,
            processors=[ResizeToFill(500,400)],
            format='PNG',
            options={'quality':80})
    title = models.CharField(max_length=200, null=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{}/{}'.format(self.album, self.title)


    class Meta:
        ordering = ['created']

explorea/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from core.validators import validate_human_name
from .models import Profile

UserModel = get_user_model()

class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=100, validators=[validate_human_name,])
    last_name = forms.CharField(max_length=100, validators=[validate_human_name,])

    class Meta:
        model = UserModel
        fields = [
            'username',
            'email',
            'first_name',
            'last_name',
            'password1',
            'password2',
        ]

class EditUserForm(UserChangeForm):
    first_name = forms.CharField(max_length=100, validators=[validate_human_name,])
    last_name = forms.CharField(max_length=100, validators=[validate_human_name,])
    
    class Meta:
        model = UserModel
        fields = [
            'username',
            'email',
            'first_name',
            'last_name',
            'password'
        ]

class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['about', 'avatar']

explorea/cart/forms.py
from django import forms

from explorea.events.models import EventRun

class PositiveIntegerField(forms.IntegerField):

    def validate(self, value):
        super().validate(value)
        if value < 1:
            raise forms.ValidationError('Only positive integer allowed')

class CartAddForm(forms.ModelForm):
    quantity = PositiveIntegerField(initial=0)
    product_id = forms.CharField(max_length=10, widget=forms.HiddenInput())
    update = forms.BooleanField(required=False, initial=False, 
                                    widget=forms.HiddenInput)
    current_quantity = forms.IntegerField(required=False, initial=0, 
                                   widget=forms.HiddenInput)

    class Meta:
        model = EventRun
        fields = [
            'quantity', 
            'product_id', 
            'update', 
            'current_quantity',
        ]

    def clean(self):
        super().clean()
        product_id = self.cleaned_data.get('product_id')
        quantity = self.cleaned_data.get('quantity')
        update = self.cleaned_data.get('update')
        current_quantity = 0 if update else  self.cleaned_data.get('current_quantity')
        
        if all([product_id, quantity]) and current_quantity >= 0:
            
            try:
                run = self._meta.model.objects.get(pk=int(product_id))

                if run.seats_available < int(quantity) + int(current_quantity):
                    self.add_error('quantity', 'Not enough items available')
            except self._meta.model.DoesNotExist:
                self.add_error('product_id', 'Requested item does not exist')

explorea/cart/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView, FormView, View
from django.views.generic.detail import SingleObjectMixin
from django.contrib import messages

from explorea.events.models import Event, EventRun
from .forms import CartAddForm


class CartDetailView(TemplateView):
    template_name = "cart/cart_detail.html"


class CartAddView(SingleObjectMixin, FormView):
    model = Event
    form_class =  CartAddForm
    template_name = 'events/event_detail.html'
    slug_url_kwarg = 'event_slug'

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def get_success_url(self):
        return self.object.get_absolute_url()

    def form_valid(self, form):

        self.request.cart.add(**form.cleaned_data)

        if form.cleaned_data['update']:
            messages.success(self.request, 'Cart has been updated')
            return redirect('cart:detail')
        else:
            messages.success(self.request, 'The run has been added to the cart')
            return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form):
        if form.cleaned_data['update']:
            messages.error(self.request, 'The cart could not be updated')
            return redirect('cart:detail')
        else:
            messages.error(self.request, 'The run could not be added into the cart')
            return HttpResponseRedirect(self.get_success_url())        
        

class CartRemoveView(View):

    def get(self, request, *args, **kwargs):
        self.request.cart.remove(self.kwargs['product_id'])
        return redirect('cart:detail')

explorea/templates/events/create_event.html
{% extends "base.html" %}

{% block content %}
<div>

  <h2>Edit event {{ event.name }}</h2>
  
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {% for field in form.visible_fields %}
        <p>{{ field.label_tag}}{{ field }}</p>
        {% for error in field.errors %}
            {{ error }}
        {% endfor %}      
    {% endfor %}

    <button type="submit">Save</button>

  </form>
  
</div>
{% endblock content %}

explorea/templates/events/create_event_run.html
{% extends "base.html" %}

{% block content %}

<h2>New Run</h2>

<form method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock content %}

explorea/templates/events/event_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <button type="submit">Delete</button>
    <a class="button-gold " href="{{ object.get_absolute_url }}">Cancel</a>
</form>
{% endblock %}

explorea/templates/events/event_detail.html
{% extends 'base.html' %}

{% load event_tags %}
{% load cart_tags %}

{% block content %}

<h2>{{ event.name }} 
    {% if run.event.host is user %}
    | <a class='edit-button' href="{% url 'events:update_event' event.slug %}">UPDATE</a> 
    | <a class='edit-button' href="{% url 'events:delete_event' event.slug %}">DELETE</a>
    {% endif %}
</h2>

<table>
    <tr>
        <th>{{ event.host }}</th><th>{{ event.location }}</th><th>{{ event.category }}</th>
    </tr>
</table>

<div class="main-image">
{% if event|has:'main_image' %}
<img src="{{ event.main_image.url }}">
{% else %}
<div class="not-available"></div>
{% endif %}
</div>

<p>{{ event.description }}</p>

<!--Image slideshow-->
<div class="owl-carousel">
{% for image in event.album.image_set.all %}
<img src="{{ image.image.url }}" alt="{{ image.title }}">
{% endfor %}
</div>

<hr>

<h2>Availability</h2>

<table>
    <th>DATE</th><th>SEATS</th><th>PRICE</th>
{% for run in runs %}
 <tr>
      <td>{{ run.date }}, {{ run.time }}</td>
      <td>{{ run.seats_available }}</td>
      <td>{{ run.price }}</td>

      {% if run.event.host is user %}
      <td><a class='edit-button' href="{% url 'events:update_event_run' run.event.slug run.id %}">CHANGE</a></td>
      <td><a class='edit-button' href="{% url 'events:delete_event_run' run.event.slug run.id %}">DELETE</a></td>
      {% else %}
      <td>
        <div>
          <form class='cart-add' method='POST' action="{% url 'cart:add' run.event.slug %}">
            {% csrf_token %}
            {{ cart_add_form.quantity }}
            {# {{ cart_add_form.current_quantity }} #} 
            <input name="current_quantity" value="{% get_key cart run.id %}" type="hidden">
            <input name="product_id" value={{ run.id }} type="hidden">
            <button type='submit'>Add to Cart</button>
          </form>
        </div>
      </td>
      {% endif %}
 </tr>
{% endfor %}
</table>

<br>

<a href="{% url 'events:events' 'all' %}">Back to Events</a> | <a href="{% url 'events:create_event_run' event.slug %}">Add New</a>
{% endblock content %}

explorea/templates/events/event_listing.html
{% extends 'base.html' %}
{% load event_tags %}

{% block title %}
<title>Event Listing</title>
{% endblock title %}

{% block content %}
<div class="thin-banner">
    <h1>What do we have here ...</h1>
</div>

<form class="event-filters"  action={{ request.get_full_path }} method="GET">

    {% for hidden_field in form.hidden_fields %}
        {{ hidden_field }}
    {% endfor %}

    {% for field in filter_form.visible_fields %}
        <div class="form-filter">
            {{ field.label_tag }} {{ field }}
        </div>
        
        <div class="errors" for={{ field.name }}>
            {% for error in field.errors %}
            <div class="error" >
                {{ error }}
            </div>
            {% endfor %}
        </div>
        
        
    {% endfor %}
   
    <button type="submit">Filter</button>
</form>

<div class="event-category-filters">
    <!--by clicking these buttons we should be taken to event listing, that show us only events of the given event category-->
    <a class="button-gold" href="{% url 'events:events' 'fun' %}">Fun</a>
    <a class="button-gold" href="{% url 'events:events' 'experience' %}">Experience</a>
    <a class="button-gold" href="{% url 'events:events' 'sights' %}">Sights</a>
    <a class="button-gold" href="{% url 'events:events' 'relax' %}">Relax</a>
    <a class="button-gold" href="{% url 'events:events' 'all' %}">All</a>
</div>

<div class="tile-container">
    {% if event_runs %}
    <div class="tile-grid">

            {% for eventrun in event_runs %}
                <a class="event-tile" href="{{ eventrun.event.get_absolute_url }}">
                    {% if eventrun.event|has:'thumbnail' %}
                        <img src="{{ eventrun.event.thumbnail.url }}">
                    {% else %}
                    <div class="not-available"></div>
                    {% endif %}
                    <div class="event-details">
                        <p>{{ eventrun.event.host }}</p>
                        <p>{{ eventrun.event.name }}</p>
                        <p>{{ eventrun.event.location}}</p>
                        <p><strong>Next:</strong> {{ eventrun.date }}</p>
                        <p><strong>Price:</strong> $ {{ eventrun.price }}</p>
                        <p><strong>Seats:</strong> {{ eventrun.seats_available }}</p>
                        <hr>
                        <p><strong>Price From:</strong> $ {{ eventrun.event.eventrun_set.all|active|min_attr_value:"price" }}</p>
                        <p><strong>Seats Up To:</strong> {{ eventrun.event.eventrun_set.all|active|max_attr_value:"seats_available" }}</p>
                    </div>
                </a>        
            {% endfor %}

    {% else %}
        <div class="info empty-search">No events found ...</div>
    {% endif %}
    </div>
</div>

{% include 'pagination.html' with page=page_obj %}

{% endblock content %}

explorea/templates/events/eventrun_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete the event run for <strong>"{{ object.event }}"</strong> on <strong>{{ object.date }}</strong>?</p>
    <button type="submit">Delete</button>
    <a class="button-gold " href="{{ object.event.get_absolute_url }}">Cancel</a>
</form>
{% endblock %}

explorea/templates/events/index.html
{% extends "base.html" %}

{% block content %}


<div class="main-banner">
    <p class="claim">Let's do something</p>
    <a href="{% url 'events:events' 'fun' %}">Fun</a>
    <a href="{% url 'events:events' 'experience' %}">Experience</a>
    <a href="{% url 'events:events' 'sights' %}">Sights</a>
    <a href="{% url 'events:events' 'relax' %}">Relax</a>
</div>


{% endblock %}

explorea/templates/events/my_events.html
{% extends 'base.html' %}

{% block title %}
<title>My Events</title>
{% endblock title %}

{% block content %}
<h2>My Events</h2>
<a href="{% url 'events:create_event' %}">ADD EVENT</a>
    <table style="text-align:center;">
        <tr>
        <th>NAME</th><th>LOCATION</th>
        </tr>
    {% for event in events %}
        <tr>
            <td><a href="{% url 'events:detail' event.slug %}">{{ event.name }}</a></td>
            <td> {{ event.location}}</td>
            <td><a href="{% url 'events:update_event' event.slug %}">UPDATE</a></td>
            <td><a href="{% url 'events:delete_event' event.slug %}">DELETE</a></td>
        </tr>
    {% endfor %}
    </table>
{% endblock content %}

explorea/templates/events/update_event_run.html
{% extends "base.html" %}

{% block content %}

<h2>{{ form.instance.event.name }}</h2>

<form method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock content %}